### ISSUE TITLE
Current Status of Repo does not have User Based Authentication

### ISSUE THREAD

**Issue by kozlowskik** [smacademic/project-GEEKS#18]
There was some discussion at the end of class on 2/28/2019 that included pulling in the user based authentication from Team DOS' implementation of Gradebook from the last semester.  
This would make it so that every user would have their own `username` and `password` that would be assigned in the Database.  
<br>
Doing this would add the following functionality:
- Make it so that there are no shared usernames or passwords associated with multiple end users.
- Provide a way to setup Role Based Access Control in the future.
- Make it so that users are accountable for any actions that are performed in the DB.
- Can lead to an implementation where the information for the DB is not displayed on the website to increase the *security* of the application.
<br><br>
---
##### ToDo:
- [x] Locate the section of code from the Team DOS Gradebook repo.
- [x] Transfer the code into the current repo
- [ ] Setup an **admin** ` username` and `password` (for development team) for the repo so that it can be tested

**Comment by kozlowskik** [comment]
Issue was completed with the commits from PR #22  being pulled into the `features` branch
